language: node_js
node_js:
  - "node"
dist: trusty
sudo: required

branches:
  only:
    - master

services:
  - docker

before_install:
  - ./ci-cd-scripts/environment_information.sh

before_script:
  - npm install -g @angular/cli

script:
  - echo "Starting backend build"
  - ./ci-cd-scripts/build_node.sh $DOCKER_USERNAME $DOCKER_PASSWORD
  - echo "Starting frontend build"
  - ./ci-cd-scripts/build_angular.sh $DOCKER_USERNAME $DOCKER_PASSWORD
