language: node_js
node_js:
  - "node"
dist: trusty
sudo: required

branches:
  only:
  - master

services:
  - docker

before_install:
- ./ci-cd-scripts/environment_information.sh

script:
- echo "Build currently undefined"